[612] - Integrate cypress testing into release-action workflow 82

diff --git a/.github/workflows/release-action.yml b/.github/workflows/release-action.yml
--- a/.github/workflows/release-action.yml
+++ b/.github/workflows/release-action.yml
@@ -66,7 +66,7 @@ jobs:
         git submodule init
         git submodule update 
         mv benefit-finder/manifest.yml benefit-finder/manifest.yml.tpl
-        export CIRCLE_BRANCH="dev"
+        export CIRCLE_BRANCH="dev" # This step makes sure this pipeline can deploy to the dev environment
         envsubst < benefit-finder/manifest.yml.tpl > benefit-finder/manifest.yml
         export NVM_DIR="$HOME/.nvm"
         [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
@@ -105,8 +105,8 @@ jobs:
         echo "removing usagov_benefit_finder directory.................."
         rm -r usagov_benefit_finder
         tar -xzvf "benefit-finder-module-${{ github.event.inputs.tag_name }}.tar.gz"
-        test -d usagov_benefit_finder/modules/usagov_benefit_finder_app/usagov_benefit_finder_page/css || { echo "ERROR!!! There is no css directory in the zip file"; }
-        test -d usagov_benefit_finder/modules/usagov_benefit_finder_app/usagov_benefit_finder_page/js || { echo "ERROR!!! There is no js directory in the zip file"; exit 1; }
+        test -d usagov_benefit_finder/modules/usagov_benefit_finder_app/usagov_benefit_finder_page/css || { echo "ERROR!!! There is no css files in the zip file"; }
+        test -d usagov_benefit_finder/modules/usagov_benefit_finder_app/usagov_benefit_finder_page/js || { echo "ERROR!!! There is no js files in the zip file"; exit 1; }
 
     - name: Setting and pushing Version Tag
       run: |
