[612] - Integrate cypress testing into release-action workflow 78

diff --git a/.github/workflows/release-action.yml b/.github/workflows/release-action.yml
--- a/.github/workflows/release-action.yml
+++ b/.github/workflows/release-action.yml
@@ -102,15 +102,13 @@ jobs:
 
     - name: Checking if the zip file has all the items expected
       run: |
-        # pwd
-        # ls -l
-        echo "removing usagov_benefit_finder"
+        echo "removing usagov_benefit_finder.................."
         rm -r usagov_benefit_finder
-        # ls -l
-        tar -xzvf "benefit-finder-module-${{ github.event.inputs.tag_name }}.tar.gz"
-        # ls -l
-        test -d usagov_benefit_finder/modules/usagov_benefit_finder_app/usagov_benefit_finder_page/css || { echo "ERROR!!! There is no css directory in the zip file"; exit 1; }
-        test -d usagov_benefit_finder/modules/usagov_benefit_finder_app/usagov_benefit_finder_page/jss || { echo "ERROR!!! There is no js directory in the zip file"; exit 1; }
+        cp "benefit-finder-module-${{ github.event.inputs.tag_name }}.tar.gz" "testing-benefit-finder-module-${{ github.event.inputs.tag_name }}.tar.gz"
+        ls -l
+        tar -xzvf "testing-benefit-finder-module-${{ github.event.inputs.tag_name }}.tar.gz"
+        test -d usagov_benefit_finder/modules/usagov_benefit_finder_app/usagov_benefit_finder_page/css || { echo "ERROR!!! There is no css directory in the zip file"; }
+        test -d usagov_benefit_finder/modules/usagov_benefit_finder_app/usagov_benefit_finder_page/js || { echo "ERROR!!! There is no js directory in the zip file"; exit 1; }
  
       
 
