[612] - Integrate cypress testing into release-action workflow 75

diff --git a/.github/workflows/release-action.yml b/.github/workflows/release-action.yml
--- a/.github/workflows/release-action.yml
+++ b/.github/workflows/release-action.yml
@@ -102,19 +102,19 @@ jobs:
 
     - name: Checking if the zip file has all the items expected
       run: |
-        pwd
-        ls -l
+        # pwd
+        # ls -l
         echo "removing usagov_benefit_finder"
         rm -r usagov_benefit_finder
-        ls -l
+        # ls -l
         tar -xzvf "benefit-finder-module-${{ github.event.inputs.tag_name }}.tar.gz"
-        ls -l
-        test -d usagov_benefit_finder/modules/usagov_benefit_finder_app/usagov_benefit_finder_page/css || { echo "Error: There is no css directory in the zip file"; exit 1; }
-        test -d usagov_benefit_finder/modules/usagov_benefit_finder_app/usagov_benefit_finder_page/js || { echo "Error: There is no js directory in the zip file"; exit 1; }
-        cd usagov_benefit_finder/modules/usagov_benefit_finder_app/usagov_benefit_finder_page
-        ls -l
-        cd usagov_benefit_finder_page
-        ls -l
+        # ls -l
+        test -d usagov_benefit_finder/modules/usagov_benefit_finder_app/usagov_benefit_finder_page/cs || { echo "Error: There is no css directory in the zip file"; exit 1; }
+        # test -d usagov_benefit_finder/modules/usagov_benefit_finder_app/usagov_benefit_finder_page/js || { echo "Error: There is no js directory in the zip file"; exit 1; }
+        # cd usagov_benefit_finder/modules/usagov_benefit_finder_app/usagov_benefit_finder_page
+        # ls -l
+        # cd usagov_benefit_finder_page
+        # ls -l
       
 
 
